# Generated by Django 5.0.6 on 2024-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='nome',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
