# Generated by Django 5.0.6 on 2024-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_cadastrocliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='email',
            field=models.EmailField(max_length=512, unique=True),
        ),
    ]
