# Generated by Django 5.0.6 on 2024-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_cadastrocliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
