# Generated by Django 5.0.6 on 2024-05-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_rename_data_nascimento_cadastrocliente_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='criado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
