# Generated by Django 5.0.6 on 2024-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_cadastrocliente_atualizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
