# Generated by Django 5.0.6 on 2024-05-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_cadastrocliente_modificado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrocliente',
            old_name='atualizado_por',
            new_name='atualizado_em',
        ),
    ]
