# Generated by Django 5.0.6 on 2024-05-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_rename_atualizado_por_cadastrocliente_atualizado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrocliente',
            old_name='atualizado_em',
            new_name='modificado_em',
        ),
    ]
