version: "3.9"
services:
  django:
    build:
      context: .
      dockerfile: django.dockerfile
    container_name: django
    restart: always
    env_file: .env
    ports:
      - 8000:8000
    networks:
      - minha-rede
    volumes: 
      - ./django-app:/django-app
      - ./web/static:/web/static
    depends_on:
      - psql

  psql:
    image: postgres:15.7-bullseye
    container_name: psql
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - minha-rede
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

networks:
  minha-rede:
    driver: bridge